version: '2'
services:
  web:
    build: .
    command: npm run init
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PORT: 3000
      SECRET: 'mysecret'
      DATABASE_NAME: 'cashflow'
      DATABASE_USERNAME: 'cashflow'
      DATABASE_PASSWORD: 'cashflow'
      DATABASE_HOST: 'postgres'
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: 'cashflow'
      POSTGRES_DB: 'cashflow'
